export { genAI, MODEL_VERSION, model } from './client'
export type { RoastMode } from './prompts'
export { buildRoastPrompt, MODERATION_PROMPT } from './prompts'
export type { ModerationResult, RoastResult } from './roast'
export { generateRoast, moderateDrama } from './roast'
